#!/usr/bin/env bash
# install nginx on your web-01 server

apt-get update -y
apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/error-404.html
sed -i '/listen 80 default_server/a error_page 404 /error404.html;\nlocation =  /error-404.html {\n\troot /var/www/html/;\n\tinternal;\n}' /etc/nginx/sites-available/default
service nginx restart
