#!/usr/bin/env bash
# Bash script with the minimum number of commands to automate your fix.

apt-get -y update
apt-get -y install nginx
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start