#!/usr/bin/env bash
#Bash script that gives you
#information about the school file
if [[ -e "school" ]]
then
    echo "school file exists"
    if [[ -s "school" ]]
    then
        echo "school file is empty"
    else
        echo "school file is not empty"
    fi
    if [[ -f "school" ]]
        echo "school is a regular file"
    if
else
    echo "school file does not exist"
fi