#!/usr/bin/env bash
# Be sure to read the Docker concept page
# In this first debugging project, you will
# need to get Apache to run on the container
# and to return a page containing Hello
# Holberton when querying the root of it.

echo "ServerName 127.0.0.1" >> /etc/apache2/apache2.conf
echo "Hello Holberton" > /var/www/html/index.html
sudo service apache2 restart
