#!/usr/bin/env bash
# Your machine has an SSH configuration
# file for the local SSH client, let’s
# configure it to our needs so that you
# can connect to a server without typing
# a password. Share your SSH client
#configuration in your answer file.

Host ubuntu@34.73.255.122
     HostName 34.73.255.122
     User ubuntu
     IdentityFile ~/.ssh/school
