#!/usr/bin/env bash
# Your machine has an SSH configuration
# file for the local SSH client, let’s
# configure it to our needs so that you
# can connect to a server without typing
# a password. Share your SSH client
#configuration in your answer file.

Host ubuntu@35.231.150.24
     HostName 35.231.150.24
     User ubuntu
     IdentityFile ~/.ssh/school
